# Generated by Django 6.0.6 on 2026-06-17 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30, verbose_name='显示名')),
                ('role', models.CharField(default='花果山 · 新客', max_length=40, verbose_name='身份')),
                ('avatar_char', models.CharField(default='客', max_length=2, verbose_name='头像单字')),
                ('avatar_color', models.CharField(choices=[('vermillion', '朱砂'), ('dark', '墨黑'), ('jade', '翡翠'), ('gold', '古铜')], default='vermillion', max_length=20, verbose_name='头像配色')),
                ('bio', models.TextField(blank=True, max_length=200, verbose_name='简介')),
                ('post_count', models.IntegerField(default=0, verbose_name='文章数')),
                ('follower_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('following_count', models.IntegerField(default=0, verbose_name='关注数')),
                ('essence_count', models.IntegerField(default=0, verbose_name='精华数')),
                ('score', models.IntegerField(default=0, verbose_name='积分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '关注关系',
                'verbose_name_plural': '关注关系',
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
